### ISSUE TITLE
nvdla_tb_sim_cfg.py SyntaxError

### ISSUE THREAD

**Issue by kouzhentao** [nvdla/hw#209]
Hi,

When ./verif/tools/run_test.py -P nv_small dc_24x33x55_5x5x55x25_int8_0 -outdir dc_24x33x55_5x5x55x25_int8_output -wave -v nvdla_utb

Traceback (most recent call last):
  File "./verif/tools/run_test.py", line 11, in <module>
    import nvdla_tb_sim_cfg
  File "/home/usr/kouzhentao/nvdla/hw/verif/tools/nvdla_tb_sim_cfg.py", line 221
    SB_CFG = { **CDMA_SB_CFG, 
                ^
SyntaxError: invalid syntax

thanks.

**Comment by ic7x24** [comment]
please check your python version. NVDLA `master` branch requires Python3 in your $PATH.

**Comment by xldeng-chn** [comment]
> 
> 
> Hi,
> 
> When ./verif/tools/run_test.py -P nv_small dc_24x33x55_5x5x55x25_int8_0 -outdir dc_24x33x55_5x5x55x25_int8_output -wave -v nvdla_utb
> 
> Traceback (most recent call last):
> File "./verif/tools/run_test.py", line 11, in
> import nvdla_tb_sim_cfg
> File "/home/usr/kouzhentao/nvdla/hw/verif/tools/nvdla_tb_sim_cfg.py", line 221
> SB_CFG = { **CDMA_SB_CFG,
> ^
> SyntaxError: invalid syntax
> 
> thanks.

Have you solved this problem? I also met this problem now. I don't know what 's wrong. I have already included python3.6 in my $PATH and tree.make python path.

![image](https://user-images.githubusercontent.com/46962066/113798684-3e34ed80-9786-11eb-9e70-04d88cf97600.png)

![image](https://user-images.githubusercontent.com/46962066/113798776-6886ab00-9786-11eb-9c45-8ce5f492c067.png)


but the problem still exists
![image](https://user-images.githubusercontent.com/46962066/113798940-b00d3700-9786-11eb-8944-ee3161c2b55a.png)
